version: '2.0'
services:
    redis:
        image: redis:alpine
        container_name: pimcore-redis

    db:
        image: mariadb:10.1
        container_name: pimcore-mariadb
        working_dir: /application
        command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb_file_format=Barracuda, --innodb_large_prefix=1, --innodb_file_per_table=1]
        volumes:
            - pimcore-database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=pimcore
            - MYSQL_USER=pimcore
            - MYSQL_PASSWORD=pimcore
        ports:
            - "3333:3306"

    php:
        build: ./.docker/php
        container_name: pimcore-php
        volumes:
            - ./:/var/www/app
            - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - db

    web:
        image: nginx:latest
        container_name: pimcore-web
        volumes:
            - ./:/var/www/app
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8888:80"
        depends_on:
            - php

volumes:
    pimcore-database:
